### ISSUE TITLE
Test suite is failing on newer versions of ruby

### ISSUE THREAD

**Issue by rmacklin** [miyagawa/rack-vcr#7]
Hi @miyagawa 👋 

First of all, thanks for making this gem! I've been using it for a couple years with great success.

Recently I ran into an issue after upgrading rack. Before digging into that issue, I wanted to see if I could run the test suite locally so that I knew I'd be starting from a green build. Unfortunately, it seems that although CI ([running ruby 2.2](https://github.com/miyagawa/rack-vcr/blob/5cb83c89598c79eec86b66b539d0c5b0d6d5970d/.travis.yml#L3)) is currently passing, there is a test that fails when running on ruby >= 2.4 - see https://travis-ci.org/github/miyagawa/rack-vcr/builds/668545594 and https://github.com/miyagawa/rack-vcr/pull/6.

I have a few questions:
1. First are foremost, are you still interested in maintaining this gem? If not, I can fork and you can ignore the rest of the questions.
2. Are you familiar with the webmock test that's failing and would you want to fix it? If not, I can try to look into it. (I haven't been using rack-vcr with webmock, so I'm not familiar with what the integration is and what we want the test to verify.)
3. Do you think we should update the Travis CI configuration to test against a more recent ruby version? Or perhaps even test against multiple ruby versions? I'd be happy to open a PR to help with this.
4. On a related note, would you be open to testing against multiple versions of rack? As mentioned above, I ran into an issue after upgrading from rack 2.0 to 2.2 (I verified that the issue was actually introduced in rack 2.1), so I think testing against multiple rack versions might be helpful to catch these types of problems. We could use [the appraisal gem](https://github.com/thoughtbot/appraisal) to do this if we also want to make it easy to run the same tests locally. I'd also be open to help here.

Thanks again for your work on this gem and I look forward to hearing from you!

**Comment by rmacklin** [comment]
Hi @miyagawa! I wanted to check in on this again -  are you still interested in maintaining this gem? If not, I can fork the gem and close this issue.

**Comment by miyagawa** [comment]
Hi @rmacklin sorry it took this long to reply to you. I personally don't use this gem and am not interested in its feature development. That said, if there's a trivial fix to make this gem compatible to Rack 2.2, or more recent versions of Ruby, i'm happy to apply the fix and release it to Rubygems.

I searched for the error message of that CI build and got https://github.com/bblimke/webmock/issues/683 Looks like the fix is to upgrade the webmock dependency?

**Comment by miyagawa** [comment]
I just pushed a few commits that should address the CI issues, and added the matrix for testing on multiple versions of Ruby. Since this is a test suite only fix, I don't think i need to push the new version of the gem. Let me know if you have any other quesitons.

**Comment by rmacklin** [comment]
Awesome, thank you! I can work on a PR to fix the issue with newer versions of rack.

**Comment by rmacklin** [comment]
> 4\. On a related note, would you be open to testing against multiple versions of rack?

I've opened https://github.com/miyagawa/rack-vcr/pull/9 to enable this

**Comment by rmacklin** [comment]
> @miyagawa commented on Aug 25
> That said, if there's a trivial fix to make this gem compatible to Rack 2.2, or more recent versions of Ruby, i'm happy to apply the fix and release it to Rubygems.

> @rmacklin commented on Aug 25
> I can work on a PR to fix the issue with newer versions of rack.

Sorry it took me a while, but here is that PR: https://github.com/miyagawa/rack-vcr/pull/10
